### ISSUE TITLE
svn links dont exist anymore.

### ISSUE THREAD

**Issue by KeksNino** [NyarchLinux/Nyarcher#6] opened 2024-10-03 19:11 UTC
all the github links in the install script dont work anymore. f.e.: svn checkout https://github.com/NyarchLinux/NyarchLinux/trunk/Gnome/etc/skel/.local/share/backgrounds doesnt exist anymore and makes the script not work properly

**Comment by KeksNino** [comment] 2024-10-03 19:12
svn: E170013: Unable to connect to a repository at URL 'https://github.com/NyarchLinux/NyarchLinux/trunk/Gnome/etc/skel/.local/share/backgrounds'
svn: E160013: '/NyarchLinux/NyarchLinux/trunk/Gnome/etc/skel/.local/share/backgrounds' path not found

**Comment by FrancescoCaracciolo** [comment] 2024-10-03 19:14
Duplicate of #4

**Closed by FrancescoCaracciolo** 2024-10-03 19:14 UTC
